name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: |
         echo "${{ secrets.ghcr }}" | docker login ghcr.io -u "ramesh-m99" --password-stdin
         docker build . --file Dockerfile --tag  test ghcr.io/ramesh-m99/test:latest
         docker push ghcr.io/ramesh-m99/test
